// Automatically generated by astro-icon
// 76c3bbfed7e2b34428c31881590566739a98b36a7c96e19089f65065f538b6e1

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arc"
		| "cake"
		| "chatgpt"
		| "close"
		| "figma"
		| "github"
		| "linkedin"
		| "location"
		| "mail"
		| "menu"
		| "notion"
		| "obsidian"
		| "phone"
		| "round"
		| "rss"
		| "twitter"
		| "vscode";
}